set MATLAB=C:\Program Files\MATLAB\R2019b
"C:\IPG\carmaker\win64-9.1\bin\cmmake" -f UNICARPTControl.mk  EXT_MODE=0 EXTMODE_STATIC_ALLOC=0 TMW_EXTMODE_TESTING=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 MAT_FILE=0 CM_VEHICLECLASS="Car" COMBINE_OUTPUT_UPDATE_FCNS=1 INCLUDE_MDL_TERMINATE_FCN=1 MULTI_INSTANCE_CODE=1 ISPROTECTINGMODEL=NOTPROTECTING OPTS="-DRT_MALLOC"
